=== audringomes/dmdw/DMDW-Datamodel-Update-1.4.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dmdw="https://github.com/boogert-lab/dmdw" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/boogert-lab/dmdw DMDW-Datamodel-Update-1.4.xsd">
  <xs:element name="datamodel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="global_properties">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="commonfields">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="group" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element name="field" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="name"/>
                                <xs:element type="xs:string" name="external_name" minOccurs="0"/>
                                <xs:element type="xs:string" name="description"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="geometry_mappings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="mapping" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="method"/>
                          <xs:element type="xs:string" name="description"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="category">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="collection">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="description"/>
                    <xs:element name="field" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="name"/>
                          <xs:element type="xs:string" name="description"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:float" name="schema_version"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== audringomes/dmdw/modules/camdb_doc_writer/resources/base/example_update/update_example.xml
<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<datamodel xmlns:dmdw="https://boogert-lab.nl/dmdw" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DMDW-Datamodel-Update-1.4.xsd" schema_version="1.4">
  <global_properties>
    <commonfields>
      <group name="Internal fields">
	<field>
	  <name>rwo_id</name>
	  <external_name>RWO ID</external_name>
	  <description>A unique foreign key for joins to geometries</description>
	</field>
	<field>
	  <name>ds!version</name>
	  <description>ds!version is an internal value used in conflict resolution.</description>
	</field>
      </group>
      <group name="New Group"/>
    </commonfields>
    <geometry_mappings>
      <mapping>
	<method>image_type</method>
	<description>Geometry mapped by Image Type</description>
      </mapping>
      <mapping>
	<method/>
	<description/>
      </mapping>
    </geometry_mappings>
  </global_properties>
  <category>
    <collection name="level_crossing">
      <description>A level crossing is an object that marks a crossing in the Rail Network without split</description>
      <field>
	<name>cost_penalty</name>
	<description>The additional costs in a trace route</description>
      </field>
      <field>
	<name/>
	<description>
	</description>
      </field>
    </collection>
  </category>
</datamodel>
